sudo: required
language: minimal

services:
  - docker

before_install:
  - docker build -t tcprescott/SpoilerTourneyBot .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
